//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tComment
    {
        public System.Guid CommentID { get; set; }
        public System.Guid VideoID { get; set; }
        public System.Guid UserID { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual tUser tUser { get; set; }
        public virtual tVideo tVideo { get; set; }
    }
}
