//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserLogin
    {
        public System.Guid UserLoginID { get; set; }
        public string UserName { get; set; }
        public string Token { get; set; }
        public string DeviceID { get; set; }
    }
}
