//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VideoEntities : DbContext
    {
        public VideoEntities()
            : base("name=VideoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tComment> tComment { get; set; }
        public virtual DbSet<tUser> tUser { get; set; }
        public virtual DbSet<tUserLogin> tUserLogin { get; set; }
        public virtual DbSet<tVideo> tVideo { get; set; }
    }
}
